# Generated by Django 3.0.5 on 2020-06-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='phone',
            field=models.CharField(default='', max_length=250),
        ),
    ]
