# Generated by Django 3.0.5 on 2020-06-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_orderproduct_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='consumer',
        ),
        migrations.AddField(
            model_name='notification',
            name='phone',
            field=models.CharField(default='', max_length=250),
        ),
    ]
