# Generated by Django 3.0.5 on 2020-06-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20200613_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='consumer',
        ),
    ]
