# Generated by Django 3.0.5 on 2020-06-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_remove_order_consumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ammount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='ammount',
            field=models.IntegerField(default=1),
        ),
    ]
